name: Building Fluentd image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths:
      - ".github/workflows/build-fd-image.yaml"
      - ".github/workflows/scan-docker-image-action.yaml"
      - "cmd/fluent-watcher/fluentd/**"
      - "cmd/fluent-watcher/hooks/**"
      - "pkg/filenotify/**"

env:
  VERSION: ${{ github.ref_name }}          # v2.2.2

  DOCKER_REGISTRY: "docker.io"
  DOCKER_REPO: "${{ vars.FD_IMG }}:${{ github.ref_name }}"                          # kubesphere/fluentd
  ARM64_DOCKER_REPO: "${{ vars.FD_IMG }}:${{ github.ref_name }}-arm64"              # kubesphere/fluentd:v2.2.2-arm64
  ARM64_BASE_DOCKER_REPO: "${{ vars.FD_IMG }}:${{ github.ref_name }}-arm64-base"    # kubesphere/fluentd:v2.2.2-arm64-base
  

  GHCR_REPO: "${{ vars.FD_GHCR_IMG }}:${{ github.ref_name }}"                              # fluent/fluentd
  ARM64_GHCR_REPO: "${{ vars.FD_GHCR_IMG }}:${{ github.ref_name }}-arm64"                  # fluent/fluentd:v2.2.2-arm64
  ARM64_BASE_GHCR_REPO: "${{ vars.FD_GHCR_IMG }}:${{ github.ref_name }}-arm64-base"        # fluent/fluentd:v2.2.2-arm64-base

jobs:
  build-fluetd-amd64:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build Fluentd amd64 docker image
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Chek if variables are defined
        run: |
          if [ -z "${{ vars.FD_IMG }}" ]; then
            echo "FD_IMG is not defined"
            exit 1
          fi

          if [ -z "${{ vars.FD_GHCR_IMG }}" ]; then
            echo "FD_GHCR_IMG is not defined"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image for Fluentd
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/fluent-watcher/fluentd/Dockerfile.amd64
          push: true
          platforms: 'linux/amd64'
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}
  
  scan-fluetd-amd64-image:
    name: Trivy + Dockle scan Fluentd amd64 docker image
    needs: 
      - build-fluetd-amd64
    uses: ./.github/workflows/scan-docker-image-action.yaml
    with:
      source_image: "${{ vars.FD_IMG }}:${{ github.ref_name }}"
      source_registry: docker.io
      platforms: '["linux/amd64"]'
    secrets:
      registry_username: ${{ secrets.REGISTRY_USER }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
  
  release-fluentd-amd64-image-to-ghcr:
    name: Release Fluentd amd64 docker image to GitHub Container Registry
    uses: ./.github/workflows/clone-docker-image-action.yaml
    needs: 
      - build-fluetd-amd64
      - scan-fluetd-amd64-image
    with:
      source_image: "${{ vars.FD_IMG }}:${{ github.ref_name }}"
      source_registry: docker.io
      target_image: "${{ vars.FD_GHCR_IMG }}:${{ github.ref_name }}"
      target_registry: ghcr.io
      platforms: '["linux/amd64"]'
    secrets:
      source_registry_username:  ${{ secrets.REGISTRY_USER }}
      source_registry_token: ${{ secrets.REGISTRY_PASSWORD }}
      target_registry_token: ${{ secrets.GITHUB_TOKEN }}
      target_registry_username: ${{ github.actor }}

  build-fluentd-arm64-base:
    runs-on: ubuntu-latest
    timeout-minutes: 90 
    name: Build Fluentd arm64 base image
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and Push Image for Fluentd
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/fluent-watcher/fluentd/Dockerfile.arm64.base
          push: true
          platforms: linux/arm64
          tags: ${{ env.ARM64_BASE_DOCKER_REPO }}

  scan-fluetd-arm64-base-image:
    name: Trivy + Dockle scan Fluentd arm64 base docker image
    needs: 
      - build-fluentd-arm64-base
    uses: ./.github/workflows/scan-docker-image-action.yaml
    with:
      source_image: "${{ vars.FD_IMG }}:${{ github.ref_name }}-arm64-base"
      source_registry: docker.io
      platforms: '["linux/arm64"]'
    secrets:
      registry_username: ${{ secrets.REGISTRY_USER }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
  
  release-fluentd-arm64-base-image-to-ghcr:
    name: Release Fluentd arm64 base docker image to GitHub Container Registry
    uses: ./.github/workflows/clone-docker-image-action.yaml
    needs: 
      - build-fluentd-arm64-base
      - scan-fluetd-arm64-base-image
    with:
      source_image: "${{ vars.FD_IMG }}:${{ github.ref_name }}-arm64-base"
      source_registry: docker.io
      target_image: "${{ vars.FD_GHCR_IMG }}:${{ github.ref_name }}-arm64-base"
      target_registry: ghcr.io
      platforms: '["linux/arm64"]'
    secrets:
      source_registry_username:  ${{ secrets.REGISTRY_USER }}
      source_registry_token: ${{ secrets.REGISTRY_PASSWORD }}
      target_registry_token: ${{ secrets.GITHUB_TOKEN }}
      target_registry_username: ${{ github.actor }}

  build-fluentd-arm64:
    runs-on: ubuntu-latest
    timeout-minutes: 90 
    name: Build Fluentd arm64 image
    needs: 
      - build-fluentd-arm64-base
      - scan-fluetd-arm64-base-image
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and Push Image for Fluentd
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/fluent-watcher/fluentd/Dockerfile.arm64.base
          push: true
          platforms: linux/arm64
          tags: docker.io/${{ vars.FD_IMG }}:${{ github.ref_name }}-arm64

  scan-fluetd-arm64-image:
    name: Scan Fluentd arm64 docker image
    needs: 
      - build-fluentd-arm64
    uses: ./.github/workflows/scan-docker-image-action.yaml
    with:
      source_image: "${{ vars.FD_IMG }}:${{ github.ref_name }}-arm64"
      source_registry: docker.io
      platforms: '["linux/arm64"]'
    secrets:
      registry_username: ${{ secrets.REGISTRY_USER }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
  
  release-fluentd-arm64-image-to-ghcr:
    name: Release Fluentd arm64 docker image to GitHub Container Registry
    uses: ./.github/workflows/clone-docker-image-action.yaml
    needs: 
      - build-fluentd-arm64
      - scan-fluetd-arm64-image
    with:
      source_image: "${{ vars.FD_IMG }}:${{ github.ref_name }}-arm64"
      source_registry: docker.io
      target_image: "${{ vars.FD_IMG }}:${{ github.ref_name }}-arm64"
      target_registry: ghcr.io
      platforms: '["linux/arm64"]'
    secrets:
      source_registry_username:  ${{ secrets.REGISTRY_USER }}
      source_registry_token: ${{ secrets.REGISTRY_PASSWORD }}
      target_registry_token: ${{ secrets.GITHUB_TOKEN }}
      target_registry_username: ${{ github.actor }}
