name: Building Fluent Bit image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths:
      - ".github/workflows/build-fb-image.yaml"
      - ".github/workflows/scan-docker-image-action.yaml"
      - "cmd/fluent-watcher/fluentbit/**"
      - "cmd/fluent-watcher/hooks/**"
      - "pkg/filenotify/**"

env:
  VERSION: ${{ github.ref_name }}   # v2.2.2

  DOCKER_REPO: "${{ vars.FB_IMG }}:${{ github.ref_name }}"                # kubesphere/fluent-bit:v2.2.2
  DOCKER_REPO_DEBUG: "${{ vars.FB_IMG }}:${{ github.ref_name }}-debug"    # kubesphere/fluent-bit:v2.2.2-debug

  GHCR_REPO: "${{ vars.FB_GHCR_IMG}}:${{ github.ref_name }}"              # fluent/fluent-watcher/fluent-bit:v2.2.2
  GHCR_REPO_DEBUG: "${{ vars.FB_GHCR_IMG}}:${{ github.ref_name }}-debug"  # fluent/fluent-watcher/fluent-bit:v2.2.2-debug

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build Image for Fluent Bit
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    
      - name: Chek if variables are defined
        run: |
          if [ -z "${{ vars.FB_IMG }}" ]; then
            echo "FB_IMG is not defined"
            exit 1
          fi

          if [ -z "${{ vars.FB_GHCR_IMG }}" ]; then
            echo "FB_GHCR_IMG is not defined"
            exit 1
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and Push Image for Fluent Bit
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/fluent-watcher/fluentbit/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.DOCKER_REPO}}
      
      - name: Build and Push Debug Image for Fluent Bit
        id: docker-build-debug
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/fluent-watcher/fluentbit/Dockerfile.debug
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.DOCKER_REPO_DEBUG }}
        
  scan-docker-image:
    name: Scan Docker Image
    needs: 
      - build
    uses: ./.github/workflows/scan-docker-image-action.yaml
    with:
      source_image: "${{ vars.FB_IMG }}:${{ github.ref_name }}"
      source_registry: docker.io
      platforms: '["linux/arm64", "linux/amd64"]'
    secrets:
      registry_username: ${{ secrets.REGISTRY_USER }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
  
  release-image-to-gchr:
    name: Release Image to GitHub Container Registry
    uses: ./.github/workflows/clone-docker-image-action.yaml
    needs: 
      - scan-docker-image
    with:
      source_image: "${{ vars.FB_IMG }}:${{ github.ref_name }}"
      source_registry: docker.io
      target_image: "${{ vars.FB_GHCR_IMG}}:${{ github.ref_name }}" 
      target_registry: ghcr.io
      platforms: "['linux/arm64', 'linux/amd64']"
    secrets:
      source_registry_username:  ${{ secrets.REGISTRY_USER }}
      source_registry_token: ${{ secrets.REGISTRY_PASSWORD }}
      target_registry_token: ${{ secrets.GITHUB_TOKEN }}
      target_registry_username: ${{ github.actor }}


  scan-debug-image:
    name: Scan Debug Image
    needs: 
      - build
    uses: ./.github/workflows/scan-docker-image-action.yaml
    with:
      source_image: "${{ vars.FB_IMG }}:${{ github.ref_name }}-debug"
      source_registry: docker.io
      platforms: '["linux/arm64", "linux/amd64"]'
    secrets:
      registry_username: ${{ secrets.REGISTRY_USER }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
      

  release-debug-image-to-gchr:
    name: Release Debug Image to GitHub Container Registry
    uses: ./.github/workflows/clone-docker-image-action.yaml
    needs: 
      - scan-debug-image
    with:
      source_image: "${{ vars.FB_IMG }}:${{ github.ref_name }}-debug"
      source_registry: docker.io
      target_image: "${{ vars.FB_GHCR_IMG}}:${{ github.ref_name }}-debug"
      target_registry: ghcr.io
      platforms: "['linux/arm64', 'linux/amd64']"
    secrets:
      source_registry_username:  ${{ secrets.REGISTRY_USER }}
      source_registry_token: ${{ secrets.REGISTRY_PASSWORD }}
      target_registry_token: ${{ secrets.GITHUB_TOKEN }}
      target_registry_username: ${{ github.actor }}
