name: Building Fluent Operator image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths:
      - ".github/workflows/build-op-image.yaml"
      - "apis/**"
      - "cmd/fluent-manager/**"
      - "controllers/**"
      - "hack/**"
      - "manifests/setup/setup.yaml"
      - "pkg/fluentd/router/**"
      - "pkg/fluentd/operator/**"
      - "pkg/fluentd/utils/**"
      - "Makefile"

env:
  VERSION: ${{ github.ref_name }}     # v0.1.0

  DOCKER_REPO: "${{ vars.FO_IMG }}:${{ github.ref_name }}"        # kubesphere/fluent-operator:v0.1.0

  FB_GHCR_IMG: "${{ vars.FO_GHCR_IMG }}:${{ github.ref_name }}"   # kubesphere/fluent-operator:v0.1.0


jobs:
  operator-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build Image for Fluent Operator
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Chek if variables are defined
        run: |

          if [ -z "${{ vars.FO_IMG }}" ]; then
            echo "FO_IMG is not defined"
            exit 1
          fi

          if [ -z "${{ vars.FO_GHCR_IMG }}" ]; then
            echo "FO_GHCR_IMG is not defined"
            exit 1
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and Push Image for Fluent Operator
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/fluent-manager/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.DOCKER_REPO}}

  scan-operator-image:
    name: Scan Docker Image
    needs: 
      - operator-build
    uses: ./.github/workflows/scan-docker-image-action.yaml
    with:
      source_image: "${{ vars.FO_IMG }}:${{ github.ref_name }}"
      source_registry: docker.io
      platforms: '["linux/arm64", "linux/amd64"]'
    secrets:
      registry_username: ${{ secrets.REGISTRY_USER }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}

  release-image-to-gchr:
    name: Release Image to GitHub Container Registry
    uses: ./.github/workflows/clone-docker-image-action.yaml
    needs: 
      - operator-build
      - scan-operator-image
    with:
      source_image: "${{ vars.FO_IMG }}:${{ github.ref_name }}"
      source_registry: docker.io
      target_image: "${{ vars.FO_GHCR_IMG}}:${{ github.ref_name }}" 
      target_registry: ghcr.io
      platforms: "['linux/arm64', 'linux/amd64']"
    secrets:
      source_registry_username:  ${{ secrets.REGISTRY_USER }}
      source_registry_token: ${{ secrets.REGISTRY_PASSWORD }}
      target_registry_token: ${{ secrets.GITHUB_TOKEN }}
      target_registry_username: ${{ github.actor }}

  # docker buildx build --push --platform linux/amd64,linux/arm64 -f cmd/fluent-manager/Dockerfile . -t ${FO_IMG}
